apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: hello-fun
  namespace: default
spec:
  tag: http://harbor.apps.dambor.com/library/hello-fun
  builder:
    name: full
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/dambor/hello-fun.git
      revision: master
